# Generated by Django 5.0.3 on 2024-03-21 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacion',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='fecha_calificacion',
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='tipo_calificacion',
        ),
        migrations.CreateModel(
            name='CalificacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_calificacion', models.DateField()),
                ('tipo_calificacion', models.CharField(max_length=50)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.calificacion')),
            ],
        ),
    ]
