# Generated by Django 5.0.3 on 2024-03-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_asignatura_cursos_asignatura_profesores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
