# Generated by Django 5.0.3 on 2024-03-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_creditoss_asignatura_creditos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='foto',
            field=models.ImageField(upload_to='profesores/'),
        ),
    ]
